### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Chuckleberry-Finn** [sharkster91/ExpandedHelicopterEvents#1]
**High Priority:**

**Low Priority:**
- [ ] Rebalance the mod entirely
- [ ] Consistency option for players
- [ ] Moodle Integration
- [ ] Dismantle empty supply drops
- [ ] Templates for vehicle scripts
- [ ] Revisit bombing as a concept to add tangible destruction
<details>
<summary> Completed Tasks: </summary>

- [x] Rewrite EHE for clientside MP
- [x] Fix the scheduler and crashes
- [x] Interactions with cars
- [x] Apply a weighted list for event spawning/chance -- to avoid over scheduling issues
- [x] maintaining tracker locations
- [x] Look into crashes farther than 200 tiles
- [x] Frequency shift crash chance
- [x] Item removal over time
- [x] Tweak marker designs -- split color like vanilla
- [x] disable events - for twitch event integration to be the only events
- [x] ~~Voice line priority to avoid repetition.~~ Would bloat the system- similar results with enough lines.
- [x] ~~Buildings as targets~~ Not feasible -8/26/21
- [x] debris fields - world item parts
- [x] Helicopter Event Selector
- [x] ~~Zombie corpses inside the helis~~ Appears to not be feasible -6/9/21
- [x] Helicopters dropping infected/other.
- [x] Siren events
- [x] hovering over drops - shift target to drops 
- [x] Weird Heli Presets: I**, S*****, U** :)
- [x] Add music capability (for raiders)
- [x] Helicopter formations
- [x] Sleep event integration
- [x] Different flight patterns beyond flybys.
- [x] Helis being able to find new nearby targets.
- [x] Jet preset
- [x] News caster/reporter chopper
- [x] Attack only chopper
- [x] Supply Heli (drops care-packages)
- [x] Helicopsters Cast Shadows
- [x] New Helicopter Helmets
- [x] Figure out how dropping flyers can best integrate into presets.
- [x] Forewarning of supply drops from AEBS
- [x] Heli-fire should damage clothes of those shot.
- [x] Implement blood spatter of those shot by the helicopter.
- [x] Write actual crash event process.
- [x] ~~Determine sites for crashes~~, if crashes can't be dynamic.
- [x] Create a vehicle that can't be repaired as the crashed heli.
- [x] Increase crash frequency
- [x] Determine loot variation in crashed helicopters
- [x] Unboxing recipes for supply boxes
- [x] Ensure at least one helicopter crash per play-through
- [x] modular crashes
</details>

\
**Nice to haves:**
- [ ] firing at helicopters? (using shadows)
- [ ] Fire integration to crashes
- [ ] flying objects (potential reuse of modular models)
- [ ] Helicopters guard the border of the exclusion zone
- [ ] Power-shutoff Integration - not currently workable
